# 透视表

In [5]:
import pandas as pd
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\employees.csv")
# 统计每一个部门的平均薪水
df.groupby('department_id').agg({'salary': 'mean'})

# 透视表
df.pivot_table(values='salary',aggfunc='mean',index='department_id')
df.pivot_table(values='salary',aggfunc='mean',columns='department_id')

department_id,10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0
salary,4400.0,9500.0,4150.0,6500.0,3475.555556,5760.0,10000.0,8955.882353,19333.333333,8600.0,10150.0

# 睡眠质量分析透视表

In [7]:
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\sleep.csv")
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [12]:
# 1）统计不同睡眠时间，不同压力等级下的睡眠质量
# 因为数据过于细致,所以对睡眠时间和压力等级进行cut分割
sleep_duration_stage = pd.cut(df['sleep_duration'],[0,5,6,7,8,9,10,11,12])
sleep_duration_stage
stress_level_stage = pd.cut(df['stress_level'],4)
stress_level_stage

df.pivot_table(values='sleep_quality',index=[sleep_duration_stage,stress_level_stage])      # 直接把对象拿过来,之前都是拿列名.但是总计margins可能会出错

                              sleep_quality
sleep_duration stress_level
(0, 5]         (0.991, 3.25]       6.781818
               (3.25, 5.5]         6.161538
               (5.5, 7.75]         5.677778
               (7.75, 10.0]        6.082353
(5, 6]         (0.991, 3.25]       5.876923
               (3.25, 5.5]         6.777778
               (5.5, 7.75]         6.058333
               (7.75, 10.0]        6.438462
(6, 7]         (0.991, 3.25]       6.472727
               (3.25, 5.5]         5.841667
               (5.5, 7.75]         5.377778
               (7.75, 10.0]        5.545455
(7, 8]         (0.991, 3.25]       6.314286
               (3.25, 5.5]         5.375000
               (5.5, 7.75]         7.280000
               (7.75, 10.0]        5.700000
(8, 9]         (0.991, 3.25]       5.423077
               (3.25, 5.5]         6.640000
               (5.5, 7.75]         5.877778
               (7.75, 10.0]        6.320000
(9, 10]        (0.991, 3.25]       5.788235
               (3.25, 5.5]         6.790000
               (5.5, 7.75]         6.010000
               (7.75, 10.0]        6.287500
(10, 11]       (0.991, 3.25]       5.853333
               (3.25, 5.5]         6.057143
               (5.5, 7.75]         6.000000
               (7.75, 10.0]        6.083333
(11, 12]       (0.991, 3.25]       6.335294
               (3.25, 5.5]         6.700000
               (5.5, 7.75]         6.071429
               (7.75, 10.0]        6.370588

In [13]:
# 2）添加职业作为列维度
df.pivot_table(values='sleep_quality', index=[sleep_duration_stage, stress_level_stage],columns='occupation')
# 2）添加职业作为列维度

occupation                    Manual Labor  Office Worker   Retired   Student
sleep_duration stress_level
(0, 5]         (0.991, 3.25]      6.900000       6.350000  6.720000  6.750000
               (3.25, 5.5]        3.300000       7.966667  6.060000  5.650000
               (5.5, 7.75]        4.833333       6.900000  3.200000  6.533333
               (7.75, 10.0]       7.200000       5.977778  5.225000  7.150000
(5, 6]         (0.991, 3.25]      5.220000       6.433333  5.700000  6.533333
               (3.25, 5.5]        5.000000       7.050000  6.900000  9.000000
               (5.5, 7.75]        6.050000       5.300000  5.300000  7.200000
               (7.75, 10.0]       6.475000       4.050000       NaN  7.100000
(6, 7]         (0.991, 3.25]      7.900000            NaN  5.866667  7.025000
               (3.25, 5.5]        4.900000       4.250000  7.600000  5.650000
               (5.5, 7.75]             NaN       5.466667  7.150000  4.425000
               (7.75, 10.0]       5.600000       6.000000  6.600000  4.720000
(7, 8]         (0.991, 3.25]      5.600000       7.700000  6.571429  5.100000
               (3.25, 5.5]        3.400000       5.033333  6.400000  6.033333
               (5.5, 7.75]        5.500000       6.600000       NaN  9.400000
               (7.75, 10.0]       5.100000       5.750000  6.071429  5.475000
(8, 9]         (0.991, 3.25]      5.100000            NaN  4.800000  5.742857
               (3.25, 5.5]        6.000000       8.100000  4.000000       NaN
               (5.5, 7.75]        4.600000            NaN  6.225000  5.850000
               (7.75, 10.0]       6.100000       5.466667  6.566667  7.240000
(9, 10]        (0.991, 3.25]      8.125000       5.200000  4.250000  5.550000
               (3.25, 5.5]        6.600000       7.500000  7.300000  5.933333
               (5.5, 7.75]        6.150000       5.466667  4.733333  8.600000
               (7.75, 10.0]       5.760000       5.540000  8.000000  6.050000
(10, 11]       (0.991, 3.25]      5.633333       5.725000  4.700000  7.300000
               (3.25, 5.5]        6.466667       5.780000  5.880000  7.100000
               (5.5, 7.75]        3.700000       6.825000  6.600000  5.900000
               (7.75, 10.0]       6.585714       6.180000  6.900000  4.675000
(11, 12]       (0.991, 3.25]      4.850000       6.171429  5.850000  7.183333
               (3.25, 5.5]        7.500000       5.600000       NaN  8.100000
               (5.5, 7.75]        5.825000       4.100000  7.550000       NaN
               (7.75, 10.0]       6.357143       6.740000  4.866667  7.750000

In [14]:
# 3）添加性别作为第二个列维度]
df.pivot_table(values='sleep_quality', index=[sleep_duration_stage, stress_level_stage],columns=['occupation','gender'])

occupation                   Manual Labor           Office Worker         \
gender                             Female      Male        Female   Male
sleep_duration stress_level
(0, 5]         (0.991, 3.25]         6.75  7.300000      6.700000  6.000
               (3.25, 5.5]           3.30       NaN      7.100000  9.700
               (5.5, 7.75]           4.55  5.400000      5.900000  7.900
               (7.75, 10.0]          8.40  6.000000      5.180000  6.975
(5, 6]         (0.991, 3.25]         5.50  4.800000      8.200000  5.550
               (3.25, 5.5]           5.00       NaN      6.600000  7.500
               (5.5, 7.75]           6.60  5.500000      4.900000  6.100
               (7.75, 10.0]          6.15  6.800000           NaN  4.050
(6, 7]         (0.991, 3.25]         7.90       NaN           NaN    NaN
               (3.25, 5.5]            NaN  4.900000           NaN  4.250
               (5.5, 7.75]            NaN       NaN      6.000000  4.400
               (7.75, 10.0]          5.60       NaN      6.600000  5.400
(7, 8]         (0.991, 3.25]         4.40  8.000000           NaN  7.700
               (3.25, 5.5]            NaN  3.400000      5.800000  4.650
               (5.5, 7.75]            NaN  5.500000           NaN  6.600
               (7.75, 10.0]          3.80  5.750000           NaN  5.750
(8, 9]         (0.991, 3.25]         5.10       NaN           NaN    NaN
               (3.25, 5.5]           6.60  5.850000      8.650000  7.550
               (5.5, 7.75]            NaN  4.600000           NaN    NaN
               (7.75, 10.0]           NaN  6.100000      4.433333  6.500
(9, 10]        (0.991, 3.25]         8.00  8.250000      4.000000  5.800
               (3.25, 5.5]           6.60       NaN      7.500000    NaN
               (5.5, 7.75]           6.15       NaN      5.750000  4.900
               (7.75, 10.0]          5.76       NaN      5.900000  5.450
(10, 11]       (0.991, 3.25]         5.85  5.200000      3.750000  7.700
               (3.25, 5.5]           6.85  5.700000      5.275000  7.800
               (5.5, 7.75]           2.80  4.600000      6.825000    NaN
               (7.75, 10.0]          5.55  7.966667      6.633333  5.500
(11, 12]       (0.991, 3.25]         4.85       NaN      4.100000  7.725
               (3.25, 5.5]            NaN  7.500000      5.600000    NaN
               (5.5, 7.75]           3.95  7.700000           NaN  4.100
               (7.75, 10.0]          6.00  6.625000      6.066667  7.750

occupation                     Retired              Student
gender                          Female       Male    Female      Male
sleep_duration stress_level
(0, 5]         (0.991, 3.25]       NaN   6.720000  6.100000  7.400000
               (3.25, 5.5]    4.850000   6.866667  5.300000  6.700000
               (5.5, 7.75]         NaN   3.200000  6.850000  5.900000
               (7.75, 10.0]   6.600000   4.766667  7.150000       NaN
(5, 6]         (0.991, 3.25]  5.700000        NaN  8.150000  3.300000
               (3.25, 5.5]    6.700000   7.100000  9.000000       NaN
               (5.5, 7.75]    4.450000   7.000000  7.066667  7.600000
               (7.75, 10.0]        NaN        NaN  7.266667  6.975000
(6, 7]         (0.991, 3.25]  6.700000   4.200000  6.566667  8.400000
               (3.25, 5.5]         NaN   7.600000  6.900000  5.400000
               (5.5, 7.75]    7.150000        NaN  5.150000  3.700000
               (7.75, 10.0]   4.900000  10.000000  4.720000       NaN
(7, 8]         (0.991, 3.25]  8.500000   5.800000  5.700000  4.500000
               (3.25, 5.5]    6.400000        NaN       NaN  6.033333
               (5.5, 7.75]         NaN        NaN       NaN  9.400000
               (7.75, 10.0]        NaN   6.071429  4.300000  9.000000
(8, 9]         (0.991, 3.25]       NaN   4.800000  6.333333  5.300000
               (3.25, 5.5]    4.000000        NaN       NaN       NaN
               (5.5, 7.75]    5.150000   7.300000  5.450000  6.250000
               (7.75, 10.0]   7.000000   6.350000  2.000000  8.550000
(9, 10]        (0.991, 3.25]  3.700000   4.800000  6.400000  5.380000
               (3.25, 5.5]    7.100000   7.400000       NaN  5.933333
               (5.5, 7.75]    2.800000   5.700000  8.600000       NaN
               (7.75, 10.0]   7.333333  10.000000       NaN  6.050000
(10, 11]       (0.991, 3.25]  4.700000   4.700000  6.933333  8.400000
               (3.25, 5.5]    4.200000   7.000000       NaN  7.100000
               (5.5, 7.75]    8.100000   5.850000  7.800000  4.633333
               (7.75, 10.0]   9.100000   4.700000  4.300000  5.050000
(11, 12]       (0.991, 3.25]       NaN   5.850000  6.566667  7.800000
               (3.25, 5.5]         NaN        NaN       NaN  8.100000
               (5.5, 7.75]    7.550000        NaN       NaN       NaN
               (7.75, 10.0]   5.200000   4.200000  9.200000  6.300000