# Python中自带的日期类型datetime

In [28]:
from datetime import datetime

date1 = datetime(year=2000, month=1, day=1)
date2 = datetime.now()
print(date1)  # 2000-01-01 00:00:00
print(date2)
print(date1.year)  # 2000
print(date1.month)  # 1
print(date1.day)  # 1
print(date2.weekday())      # 0~6星期一~星期日
print(date2.strftime("%A"))
print(date2 - date1)

2000-01-01 00:00:00
2026-09-23 11:30:32.963113
2000
1
1
2
9762 days, 11:30:32.963113

In [32]:
import pandas as pd
# 在加载数据的时候,通过parse_dates将日期字符串直接转换为TimesStamp类型
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\weather.csv",parse_dates=["date"])
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

# 提取TimeStamp的各个部分

In [33]:
d = pd.Timestamp("2015-01-01 09:08:07.123456")
print(d.year)  # 2015
print(d.month)  # 1
print(d.day)  # 1
print(d.hour)  # 9
print(d.minute)  # 8
print(d.second)  # 7
print(d.microsecond)  # 123456

2015
1
1
9
8
7
123456

In [38]:
# Series通过时间属性访问器对象访问
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\weather.csv")
df_date = pd.to_datetime(df["date"])
df['year'] = df_date.dt.year
df['month'] = df_date.dt.month
df['day'] = df_date.dt.day
df

<class 'pandas.DataFrame'>
PeriodIndex: 1461 entries, 2012Q1 to 2015Q4
Freq: Q-DEC
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
 6   year           1461 non-null   int32
 7   month          1461 non-null   int32
 8   day            1461 non-null   int32
dtypes: float64(4), int32(3), str(2)
memory usage: 97.0 KB

# Period

In [39]:
df["quarter"] = pd.to_datetime(df["date"]).dt.to_period("Q")  # 将 年-月-日 转换为 年季度
df.set_index('quarter', inplace=True)
df.info()

<class 'pandas.DataFrame'>
PeriodIndex: 1461 entries, 2012Q1 to 2015Q4
Freq: Q-DEC
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
 6   year           1461 non-null   int32
 7   month          1461 non-null   int32
 8   day            1461 non-null   int32
dtypes: float64(4), int32(3), str(2)
memory usage: 97.0 KB

# timedelta64

In [41]:
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\weather.csv")
df_date = pd.to_datetime(df["date"])
timedelta = df_date - df_date[0]
df['day-diff'] = timedelta
df.set_index('day-diff', inplace=True)
df.info()

<class 'pandas.DataFrame'>
TimedeltaIndex: 1461 entries, 0 days to 1460 days
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: float64(4), str(2)
memory usage: 79.9 KB

# 时间索引

In [51]:
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\weather.csv")
# df['date'] = pd.to_datetime(df["date"])
# df.set_index('date', inplace=True)

df.loc['2013-01':'2013-05']
# df.between_time("9:00", "11:00")  # 获取9:00到11:00之间的数据
# df.at_time("3:33")  # 获取3:33的数据

df['timedelta'] = df_date - df_date[0]
df.set_index('timedelta', inplace=True)
df.loc['0 days':'5 days']

                 date  precipitation  temp_max  temp_min  wind  weather
timedelta
0 days     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days     2012-01-02           10.9      10.6       2.8   4.5     rain
2 days     2012-01-03            0.8      11.7       7.2   2.3     rain
3 days     2012-01-04           20.3      12.2       5.6   4.7     rain
4 days     2012-01-05            1.3       8.9       2.8   6.1     rain
5 days     2012-01-06            2.5       4.4       2.2   2.2     rain

# 生成时间序列

In [63]:
pd.date_range('2015-01-01','2015-03-01')
pd.date_range('2015-01-01',periods=5)
pd.date_range('2015-01-01',periods=5,freq='h')
pd.date_range('2015-01-01',periods=5,freq='QE-FEB')
pd.date_range('2015-01-01',periods=5,freq='2h30min')

df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\weather.csv")
# 重新采样
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

df[['temp_max','temp_min']].resample('YE').mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616